"""Markdown rendering helpers."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from .inferrer import infer_column_description, infer_dataset_summary


def render_markdown(profile: dict[str, Any], *, llm_enabled: bool = False) -> str:
    """Render a profile dictionary into a Markdown document."""
    sections = [
        _render_header(profile, llm_enabled=llm_enabled),
        _render_at_a_glance(profile),
        _render_columns(profile),
        _render_quality_notes(profile),
        _render_code_snippet(profile),
        _render_footer(),
    ]
    return "\n\n".join(section for section in sections if section)


def _render_header(profile: dict[str, Any], *, llm_enabled: bool) -> str:
    summary = infer_dataset_summary(profile)
    if profile["sampled"]:
        summary += f" Statistics are based on a sample of {profile['row_count']:,} rows."
    if llm_enabled:
        summary += " AI narration is planned for a later release."
    return f"# {profile['filename']}\n\n> {summary}"


def _render_at_a_glance(profile: dict[str, Any]) -> str:
    generated = datetime.fromisoformat(profile["generation_timestamp"]).strftime("%Y-%m-%d")
    file_size = _format_size(profile.get("file_size_bytes"))
    rows_label = f"{profile['row_count']:,}"
    if profile["sampled"]:
        rows_label += " sampled"
    lines = [
        "## At a glance",
        "",
        "| | |",
        "|---|---|",
        f"| Rows | {rows_label} |",
        f"| Columns | {profile['column_count']:,} |",
        f"| File size | {file_size} |",
        f"| Duplicate rows | {profile['duplicate_row_count']:,} |",
        f"| Overall null rate | {profile['overall_null_pct']:.1f}% |",
        f"| Generated | {generated} |",
    ]
    return "\n".join(lines)


def _render_columns(profile: dict[str, Any]) -> str:
    lines = [
        "## Columns",
        "",
        "| Column | Type | Nulls | Description |",
        "|---|---|---|---|",
    ]
    for column in profile["columns"]:
        description = infer_column_description(column).replace("\n", " ").strip()
        lines.append(
            f"| `{column['name']}` | {column['dtype_display']} | {column['null_pct']:.1f}% | {description} |"
        )
    return "\n".join(lines)


def _render_quality_notes(profile: dict[str, Any]) -> str:
    notes: list[str] = []
    for column in profile["columns"]:
        if column["null_pct"] >= 50:
            notes.append(
                f"- `{column['name']}`: {column['null_pct']:.1f}% null; consider whether the field is usable."
            )
        elif column["null_pct"] >= 20:
            notes.append(
                f"- `{column['name']}`: {column['null_pct']:.1f}% null; review before analysis."
            )
        if column["flags"]["likely_computed"]:
            notes.append(
                f"- `{column['name']}`: may be a derived field; verify before treating it as source-of-truth data."
            )
        if column["flags"]["possible_pii"]:
            notes.append(
                f"- `{column['name']}`: may contain personal data; review privacy requirements before sharing."
            )
        if column["flags"]["likely_target"]:
            notes.append(
                f"- `{column['name']}`: looks like a target variable; check null handling and class balance."
            )
        if column["flags"]["mixed_type"]:
            notes.append(
                f"- `{column['name']}`: mixed value types detected; clean before strict downstream use."
            )
        if column["is_constant"]:
            notes.append(
                f"- `{column['name']}`: constant value across all non-null rows."
            )
    if profile["duplicate_row_count"] > 0:
        notes.append(f"- {profile['duplicate_row_count']:,} duplicate rows detected.")
    if not notes:
        return ""
    return "## Data quality notes\n\n" + "\n".join(notes)


def _render_code_snippet(profile: dict[str, Any]) -> str:
    lines = [
        "import pandas as pd",
        f'df = pd.read_csv("{profile["filename"]}")',
    ]
    date_columns = [
        column["name"]
        for column in profile["columns"]
        if column["dtype_display"] == "datetime"
    ]
    for name in date_columns[:3]:
        lines.append(f'df["{name}"] = pd.to_datetime(df["{name}"])')
    code = "\n".join(lines)
    return f"## How to load\n\n```python\n{code}\n```"


def _render_footer() -> str:
    return "---\n*Generated by datareadme*"


def _format_size(file_size_bytes: int | None) -> str:
    if file_size_bytes is None:
        return "Unknown"
    units = ["B", "KB", "MB", "GB"]
    size = float(file_size_bytes)
    unit = units[0]
    for unit in units:
        if size < 1024 or unit == units[-1]:
            break
        size /= 1024
    if unit == "B":
        return f"{int(size)} {unit}"
    return f"{size:.1f} {unit}"
